### ISSUE TITLE
Update code generation to match with development version of Blawx

### ISSUE THREAD

**Issue by Gauntlet173** [Blawx/docassemble-blawx#1]
the upcoming release of Blawx changes the way it encodes boolean objects. It may be necessary to make changes to how Docassemble reports them to match.

**Comment by dazzaji** [comment]
Can you expound a little more on what changes would be needed?

**Comment by Gauntlet173** [comment]
The main blawx project has gone from using "true" and "false" in Flora-2 to code to represent the boolean values to using "\true" and "\false", which is the standard usage in Flora-2. The docassemble-blawx code may still be using "true" and "false" when converting the interview data into a JSON structure to send to the API. If it is, we may need to fix that inside the docassemble-blawx code, or perhaps in the json2f2.py code in the main project. It's not totally clear to me, yet, so this issue is a reminder that if I run into problems that might be where to look.

**Comment by dazzaji** [comment]
Ok. Thanks!

**Comment by Gauntlet173** [comment]
Yeah, took a closer look and the issue is in blawx's json2f2.py file, so I'm closing here and recreating this issue there.
